## 2 кейс

**В этом кейсе вы будете рассчитывать:**
* самую эффективную платформу
* самый успешный тип рекламной кампании
* географию
* рекламные расходы по городам
* даты, в которые не запускались кампании
* и еще кое-что

**Важно**

Перед началом решения задачи выполните следующую ячейку - в ней скачиваются необходимые файлы.

Работать вы будут с файлом `campaign_data.csv`.

In [1]:
!wget https://gist.github.com/Vs8th/73045f9fe675f43ef7e63ab56f1c08bd/raw/campaign_data.csv

!wget https://gist.github.com/Vs8th/2d55f7828343a0b5e570b47552c3affe/raw/marketing_campaigns.txt

!wget https://gist.github.com/Vs8th/ff57611e607f407b186805ae15b08f1c/raw/cor_platform.txt

--2026-03-08 08:02:07--  https://gist.github.com/Vs8th/73045f9fe675f43ef7e63ab56f1c08bd/raw/campaign_data.csv
Resolving gist.github.com (gist.github.com)... 140.82.113.3
Connecting to gist.github.com (gist.github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://gist.githubusercontent.com/Vs8th/73045f9fe675f43ef7e63ab56f1c08bd/raw/campaign_data.csv [following]
--2026-03-08 08:02:07--  https://gist.githubusercontent.com/Vs8th/73045f9fe675f43ef7e63ab56f1c08bd/raw/campaign_data.csv
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 116478 (114K) [text/plain]
Saving to: ‘campaign_data.csv’

campaign_data.csv   100%[===================>] 113.75K  --.-KB/s    in 0.03s

2026-03-08 08:02:07 (4.14 MB/s) - ‘campaign_data.csv’ saved [116478/116478]

--2026-03-08 08:02:07--  https://gist.github.com/Vs8th/2d55f7828343a0b5e570b47552c3affe/raw/marketing_campaigns.txt
Resolving gist.github.com (gist.github.com)... 140.82.112.4
Connecting to gist.github.com (gist.github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://gist.githubusercontent.com/Vs8th/2d55f7828343a0b5e570b47552c3affe/raw/marketing_campaigns.txt [following]
--2026-03-08 08:02:07--  https://gist.githubusercontent.com/Vs8th/2d55f7828343a0b5e570b47552c3affe/raw/marketing_campaigns.txt
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2265 (2.2K) [text/plain]
Saving to: ‘marketing_campaigns.txt’

marketing_campaigns 100%[===================>]   2.21K  --.-KB/s    in 0s

2026-03-08 08:02:07 (35.1 MB/s) - ‘marketing_campaigns.txt’ saved [2265/2265]

--2026-03-08 08:02:07--  https://gist.github.com/Vs8th/ff57611e607f407b186805ae15b08f1c/raw/cor_platform.txt
Resolving gist.github.com (gist.github.com)... 140.82.114.3
Connecting to gist.github.com (gist.github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://gist.githubusercontent.com/Vs8th/ff57611e607f407b186805ae15b08f1c/raw/cor_platform.txt [following]
--2026-03-08 08:02:07--  https://gist.githubusercontent.com/Vs8th/ff57611e607f407b186805ae15b08f1c/raw/cor_platform.txt
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3580 (3.5K) [text/plain]
Saving to: ‘cor_platform.txt’

cor_platform.txt    100%[===================>]   3.50K  --.-KB/s    in 0s

2026-03-08 08:02:08 (59.4 MB/s) - ‘cor_platform.txt’ saved [3580/3580]

In [2]:
import pandas as pd

df = pd.read_csv('campaign_data.csv')
df

,ID Кампании,Начальная дата,Конечная дата,Тип кампании,Платформа,Бюджет,Город,Показы,Клики,Конверсия,Доход
0,1,2022-01-01,2022-11-30,Контекстная,Telegram,35693,Казань,3217.0,507.0,188,44205
1,2,2022-01-01,2022-08-27,Поисковая оптимизация,Вконтакте,1986,Москва,1362.0,305.0,95,9964
2,3,2022-01-02,2022-03-11,Баннерная,Instagram,2020,Екатеринбург,2420.0,541.0,87,14792
3,4,2022-01-02,2022-06-20,Видеореклама,Google,18684,Москва,728.0,406.0,73,13824
4,8,2022-01-04,2022-12-06,Поисковая оптимизация,Вконтакте,47936,Екатеринбург,356.0,129.0,31,3908
...,...,...,...,...,...,...,...,...,...,...,...
1015,1240,2022-12-28,2022-12-29,Видеореклама,Instagram,24525,Калуга,5610.0,732.0,93,12208
1016,1241,2022-12-28,2022-12-29,Нативная интеграция,Telegram,2904,Екатеринбург,937.0,199.0,44,2839
1017,1243,2022-12-28,2022-12-30,Нативная интеграция,Telegram,27913,Казань,9309.0,1280.0,128,30575
1018,1245,2022-12-29,2022-12-29,Поисковая оптимизация,Google,23648,Новосибирск,854.0,252.0,71,17632
1019,1246,2022-12-30,2022-12-30,Баннерная,Telegram,1909,Екатеринбург,848.0,228.0,31,4298

### **Найдите самую эффективную платформу по средним значениям конверсий**

Cохраните результат в переменную `most_effective_platform`

In [3]:
# Ваше решение
new_df = df[['Платформа', 'Конверсия']].groupby(by='Платформа', sort = True).mean()
most_effective_platform = new_df['Конверсия'].idxmax()
most_effective_platform

'Instagram'

In [4]:
#@title ✏️ Проверка: чтобы проверить свое решение запустите код в этой ячейке
# Открываем файл с правильными ответами
with open('marketing_campaigns.txt', 'r') as f:
    answers = f.read().split('\n')

correct_answer = answers[0]

try:
    assert most_effective_platform == correct_answer
except AssertionError:
    print('Ответы не совпадают')
else:
    print('Поздравляем, Вы справились!')

Поздравляем, Вы справились!

### **Найдите самый успешный тип рекламной кампании по средним значениям конверсий**

Сохраните результат в переменную `most_successful_campaign_type`

In [5]:
# Ваше решение
new_df = df[['Тип кампании', 'Конверсия']].groupby(by='Тип кампании', sort = True).mean()
most_successful_campaign_type = new_df['Конверсия'].idxmax()
most_successful_campaign_type

'Контекстная'

In [6]:
#@title ✏️ Проверка: чтобы проверить свое решение запустите код в этой ячейке
correct_answer = answers[1]

try:
    assert most_successful_campaign_type == correct_answer
except AssertionError:
    print('Ответы не совпадают')
else:
    print('Поздравляем, Вы справились!')

Поздравляем, Вы справились!

### **Найдите самый успешный город проведения кампании по средним значениям конверсий**

Сохраните результат в переменную `most_successful_city`

In [7]:
# Ваше решение
new_df = df[['Город', 'Конверсия']].groupby(by='Город', sort = True).mean()
most_successful_city = new_df['Конверсия'].idxmax()

most_successful_city

'Новосибирск'

In [8]:
#@title ✏️ Проверка: чтобы проверить свое решение запустите код в этой ячейке
correct_answer = answers[2]

try:
    assert most_successful_city == correct_answer
except AssertionError:
    print('Ответы не совпадают')
else:
    print('Поздравляем, Вы справились!')

Поздравляем, Вы справились!

### **Посчитайте долю затрат на рекламные кампании каждой платформы и каждого города**

Сохраните результат в файл `platform_city_results.txt`

Результат должен иметь такой же порядок групп, что и изначальный файл. А города внутри платформ должны быть отсортированы по убыванию доли затрат, а доля затрат должны быть округлена до 2 знаков после запятой.

Результат должен выглядеть примерно так:

```
Для группы Telegram:
- Город: Москва, доля затрат на рекламу: 16.46%
- Город: Калуга, доля затрат на рекламу: 16.2%
- Город: Казань, доля затрат на рекламу: 14.57%
- ...
Для группы Вконтакте:
- Город: Екатеринбург, доля затрат на рекламу: 17.43%
- Город: Новосибирск, доля затрат на рекламу: 14.86%
- Город: Санкт-Петербург, доля затрат на рекламу: 14.13%
...
```

In [10]:
# Ваше решение
with open('campaign_data.csv', 'r', encoding='utf-8') as file:
    lines = file.readlines()
platforms = dict()
orders = ['Telegram', 'Вконтакте', 'Instagram', 'Google', 'Яндекс']
for line in lines[1::]:
    parts = line.strip().split(',')
    platform = parts[4]
    budget = int(parts[5])
    city = parts[6]
    if platform not in platforms:
        platforms[platform] = {'total_budget':0, 'cities':{}}
    platforms[platform]['total_budget'] += budget
    if city not in platforms[platform]['cities']:
        platforms[platform]['cities'][city] = 0
    platforms[platform]['cities'][city] += budget
with open('platform_city_results.txt', 'w', encoding='utf-8') as file:
    output = []
    for platform in platforms:
        total = platforms[platform]['total_budget']
        cities = platforms[platform]['cities']
        sorted_cities = sorted(cities.items(), key = lambda x:x[1], reverse=True)
        output.append(f'Для группы {platform}:')
        for k, v in sorted_cities:
            share = round(v/total*100, 2)
            output.append(f'- Город: {k}, доля затрат на рекламу: {share}%')
    file.write('\n'.join(output))

In [ ]:
#@title ✏️ Проверка: чтобы проверить свое решение запустите код в этой ячейке

with open('platform_city_results.txt', 'r') as file:
    user_answer = file.readlines()

with open('cor_platform.txt', 'r') as file:
    correct_answer = file.readlines()

try:
    assert user_answer == correct_answer, 'Ответы не совпадают'
except Exception as err:
    raise AssertionError(f'При проверке возникла ошибка {repr(err)}')
else:
    print('Поздравляем, Вы справились и успешно прошли все проверки!!')

AssertionError: При проверке возникла ошибка AssertionError('Ответы не совпадают')

In [25]:
with open('platform_city_results.txt', 'r') as file:
    user_answer = file.readlines()

with open('cor_platform.txt', 'r') as file:
    correct_answer = file.readlines()
for i in range(len(user_answer)):
    print(i, user_answer[i]==correct_answer[i])

0 True
1 True
2 True
3 True
4 True
5 True
6 True
7 True
8 True
9 True
10 True
11 True
12 True
13 True
14 True
15 True
16 True
17 True
18 True
19 True
20 True
21 True
22 True
23 True
24 True
25 True
26 True
27 True
28 True
29 True
30 True
31 True
32 True
33 True
34 True
35 True
36 True
37 True
38 True
39 True
40 True
41 True
42 True
43 True
44 False
['-', ' ', 'Г', 'о', 'р', 'о', 'д', ':', ' ', 'К', 'р', 'а', 'с', 'н', 'о', 'д', 'а', 'р', ',', ' ', 'д', 'о', 'л', 'я', ' ', 'з', 'а', 'т', 'р', 'а', 'т', ' ', 'н', 'а', ' ', 'р', 'е', 'к', 'л', 'а', 'м', 'у', ':', ' ', '1', '0', '.', '7', '8', '%'] ['-', ' ', 'Г', 'о', 'р', 'о', 'д', ':', ' ', 'К', 'р', 'а', 'с', 'н', 'о', 'д', 'а', 'р', ',', ' ', 'д', 'о', 'л', 'я', ' ', 'з', 'а', 'т', 'р', 'а', 'т', ' ', 'н', 'а', ' ', 'р', 'е', 'к', 'л', 'а', 'м', 'у', ':', ' ', '1', '0', '.', '7', '8', '%', '\n']

### **Напишите функцию, которая возвращает средний бюджет всех кампаний, запущенных на определенной платформе**

Функция `calculate_average_budget` должна принимать путь к файлу и название плафтормы и возвращать число - средний бюджет всех кампаний, запущенных на данной платформе, округленный до двух знаков после запятой.

In [14]:

def calculate_average_budget(file_path, platform_name):
    total = count = 0

    with open(file_path, encoding='utf-8') as f:
        next(f)
        for line in f:
            parts = line.strip().split(',')
            if parts[4] == platform_name:
                total += int(parts[5])
                count += 1

    return round(total / count, 2)


calculate_average_budget('campaign_data.csv', 'Google')

25123.22

In [15]:
#@title ✏️ Проверка: чтобы проверить свое решение запустите код в этой ячейке
correct_answer = answers[3]
user_answer = str(calculate_average_budget('campaign_data.csv', 'Google'))

try:
    assert user_answer == correct_answer
except AssertionError:
    print('Ответы не совпадают')
else:
    print('Поздравляем, Вы справились!')

Поздравляем, Вы справились!

In [16]:
#@title ✏️ Еще одна проверка: чтобы проверить свое решение запустите код в этой ячейке
correct_answer = answers[4]
user_answer = str(calculate_average_budget('campaign_data.csv', 'Вконтакте'))

try:
    assert user_answer == correct_answer
except AssertionError:
    print('Ответы не совпадают')
else:
    print('Поздравляем, Вы справились!')

Поздравляем, Вы справились!

### **Напишите генератор, который будет генерировать даты, в которые НЕ запускались кампании**

Функция `get_missing_campaign_dates` должна принимать путь к файлу и генерировать построчно даты, отсортированные по возрастанию, в которые не запускались кампании, в формате:

```
2022-02-29
2022-03-28
2022-03-29
2022-05-30
2022-06-13
2022-06-27
...
```

In [26]:
df.head()

,ID Кампании,Начальная дата,Конечная дата,Тип кампании,Платформа,Бюджет,Город,Показы,Клики,Конверсия,Доход
0,1,2022-01-01,2022-11-30,Контекстная,Telegram,35693,Казань,3217.0,507.0,188,44205
1,2,2022-01-01,2022-08-27,Поисковая оптимизация,Вконтакте,1986,Москва,1362.0,305.0,95,9964
2,3,2022-01-02,2022-03-11,Баннерная,Instagram,2020,Екатеринбург,2420.0,541.0,87,14792
3,4,2022-01-02,2022-06-20,Видеореклама,Google,18684,Москва,728.0,406.0,73,13824
4,8,2022-01-04,2022-12-06,Поисковая оптимизация,Вконтакте,47936,Екатеринбург,356.0,129.0,31,3908

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID Кампании     1020 non-null   int64
 1   Начальная дата  1020 non-null   object
 2   Конечная дата   1020 non-null   object
 3   Тип кампании    1020 non-null   object
 4   Платформа       1020 non-null   object
 5   Бюджет          1020 non-null   int64
 6   Город           1020 non-null   object
 7   Показы          1020 non-null   float64
 8   Клики           1020 non-null   float64
 9   Конверсия       1020 non-null   int64
 10  Доход           1020 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 87.8+ KB

In [44]:
from datetime import datetime, date, timedelta
def get_missing_campaign_dates(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        lines = file.readlines()
    result = []
    start = date(2022, 1, 1)
    end = date(2022, 12, 30)
    calendar_days = [start+timedelta(days=i) for i in range((end-start).days+1)]
    for line in lines[1::]:
        part = line.strip().split(',')
        start_date = datetime.strptime(part[1], '%Y-%m-%d').date()
        result.append(start_date)
    set_result = (sorted(set(result)))
    missing_days = [i for i in calendar_days if i not in set_result]
    return missing_days



get_missing_campaign_dates('campaign_data.csv')

[datetime.date(2022, 1, 3),
 datetime.date(2022, 2, 13),
 datetime.date(2022, 3, 7),
 datetime.date(2022, 4, 29),
 datetime.date(2022, 5, 11),
 datetime.date(2022, 6, 9),
 datetime.date(2022, 6, 24),
 datetime.date(2022, 6, 25),
 datetime.date(2022, 6, 29),
 datetime.date(2022, 6, 30),
 datetime.date(2022, 7, 31),
 datetime.date(2022, 8, 10),
 datetime.date(2022, 8, 29),
 datetime.date(2022, 9, 8),
 datetime.date(2022, 9, 17),
 datetime.date(2022, 10, 31),
 datetime.date(2022, 11, 13),
 datetime.date(2022, 11, 27)]

In [45]:
#@title ✏️ Проверка: чтобы проверить свое решение запустите код в этой ячейке
from datetime import date

correct_answer = answers[5]

missing_dates = get_missing_campaign_dates('campaign_data.csv')
user_answer = []
for date in missing_dates:
    a = date.strftime('%Y-%m-%d')
    user_answer.append(a)

try:
    assert str(user_answer) == correct_answer
except AssertionError:
    print('Ответы не совпадают')
else:
    print('Поздравляем, Вы справились!')

Поздравляем, Вы справились!

### **Напишите функцию, которая будет принимать на вход путь к файлу и возвращать сгруппированные данные по городам, содержащие суммарный бюджет и количество кликов**

Функция `group_campaign_data` должна возвращать список словарей, отсортированный по городам, в формате:

```python
[{'Город': 'Нижний Новгород',
  'Количество кликов': 616.0,
  'Суммарный бюджет': 27585},
 {'Город': 'Новосибирск',
  'Количество кликов': 733.0,
  'Суммарный бюджет': 33001},
  ...]
```

In [18]:

def group_campaign_data(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        lines = file.readlines()
    result = []
    cities = dict()
    for line in lines[1::]:
        part = line.strip().split(',')
        city = part[6]
        budget = int(part[5])
        clicks = float(part[8])
        if city not in cities:
            cities[city] = {'clicks':0, 'budget':0}
        cities[city]['clicks'] += clicks
        cities[city]['budget'] += budget
    sorted_cities = dict(sorted(cities.items(), key=lambda x:x))
    for k, v in sorted_cities.items():
        result.append({'Город':k, 'Количество кликов':v['clicks'], 'Суммарный бюджет':v['budget']})
    return result


group_campaign_data('campaign_data.csv')

[{'Город': 'Екатеринбург',
  'Количество кликов': 82104.0,
  'Суммарный бюджет': 3742631},
 {'Город': 'Казань',
  'Количество кликов': 68353.0,
  'Суммарный бюджет': 3138271},
 {'Город': 'Калуга',
  'Количество кликов': 72801.0,
  'Суммарный бюджет': 3434585},
 {'Город': 'Краснодар',
  'Количество кликов': 63965.0,
  'Суммарный бюджет': 3165896},
 {'Город': 'Москва',
  'Количество кликов': 69939.0,
  'Суммарный бюджет': 3003448},
 {'Город': 'Нижний Новгород',
  'Количество кликов': 65416.0,
  'Суммарный бюджет': 2730585},
 {'Город': 'Новосибирск',
  'Количество кликов': 73303.0,
  'Суммарный бюджет': 3363001},
 {'Город': 'Санкт-Петербург',
  'Количество кликов': 66266.0,
  'Суммарный бюджет': 3254148}]

In [19]:
#@title ✏️ Проверка: чтобы проверить свое решение запустите код в этой ячейке
correct_answer = answers[6]
user_answer = str(group_campaign_data('campaign_data.csv'))

try:
    assert user_answer == correct_answer
except AssertionError:
    print('Ответы не совпадают')
else:
    print('Поздравляем, Вы справились!')

Поздравляем, Вы справились!

### **Напишите генератор, который будет генерировать данные о кампаниях, запущенных в указанном городе и имеющих бюджет выше заданного значения**

Функция `campaign_generator` должна принимать путь к файлу, город и бюджет и генерировать словари, отсортированные по возрастанию 'ID Кампании' в формате:

```
{'ID Кампании': '657', 'Тип': 'Контекстная', 'Платформа': 'Вконтакте', 'Доход': '10692'}
{'ID Кампании': '674', 'Тип': 'Нативная интеграция', 'Платформа': 'Яндекс', 'Доход': '20766'}
{'ID Кампании': '761', 'Тип': 'Соцсети', 'Платформа': 'Вконтакте', 'Доход': '15680'}
```

In [ ]:
df.head()

,ID Кампании,Начальная дата,Конечная дата,Тип кампании,Платформа,Бюджет,Город,Показы,Клики,Конверсия,Доход
0,1,2022-01-01,2022-11-30,Контекстная,Telegram,35693,Казань,3217.0,507.0,188,44205
1,2,2022-01-01,2022-08-27,Поисковая оптимизация,Вконтакте,1986,Москва,1362.0,305.0,95,9964
2,3,2022-01-02,2022-03-11,Баннерная,Instagram,2020,Екатеринбург,2420.0,541.0,87,14792
3,4,2022-01-02,2022-06-20,Видеореклама,Google,18684,Москва,728.0,406.0,73,13824
4,8,2022-01-04,2022-12-06,Поисковая оптимизация,Вконтакте,47936,Екатеринбург,356.0,129.0,31,3908

In [20]:
def campaign_generator(file_path, city, budget):
    with open(file_path, 'r', encoding='utf-8') as file:
        lines = file.readlines()
    result = []
    for line in lines[1::]:
        parts = line.strip().split(',')
        if city == parts[6] and budget<int(parts[5]):
            result.append({'ID Кампании':parts[0], 'Тип':parts[3], 'Платформа':parts[4], 'Доход':parts[10]})
    return result
campaign_generator('campaign_data.csv', 'Москва', 25000)

[{'ID Кампании': '21',
  'Тип': 'Нативная интеграция',
  'Платформа': 'Instagram',
  'Доход': '5626'},
 {'ID Кампании': '42',
  'Тип': 'Видеореклама',
  'Платформа': 'Telegram',
  'Доход': '11539'},
 {'ID Кампании': '102',
  'Тип': 'Баннерная',
  'Платформа': 'Вконтакте',
  'Доход': '22487'},
 {'ID Кампании': '182',
  'Тип': 'Видеореклама',
  'Платформа': 'Telegram',
  'Доход': '1441'},
 {'ID Кампании': '191',
  'Тип': 'Нативная интеграция',
  'Платформа': 'Google',
  'Доход': '10402'},
 {'ID Кампании': '197',
  'Тип': 'Соцсети',
  'Платформа': 'Вконтакте',
  'Доход': '40635'},
 {'ID Кампании': '205',
  'Тип': 'Нативная интеграция',
  'Платформа': 'Вконтакте',
  'Доход': '1814'},
 {'ID Кампании': '242',
  'Тип': 'Видеореклама',
  'Платформа': 'Яндекс',
  'Доход': '5268'},
 {'ID Кампании': '246',
  'Тип': 'Нативная интеграция',
  'Платформа': 'Telegram',
  'Доход': '28537'},
 {'ID Кампании': '305',
  'Тип': 'Контекстная',
  'Платформа': 'Instagram',
  'Доход': '6600'},
 {'ID Кампании': '324',
  'Тип': 'Соцсети',
  'Платформа': 'Telegram',
  'Доход': '23280'},
 {'ID Кампании': '396',
  'Тип': 'Баннерная',
  'Платформа': 'Яндекс',
  'Доход': '5938'},
 {'ID Кампании': '430',
  'Тип': 'Поисковая оптимизация',
  'Платформа': 'Telegram',
  'Доход': '3102'},
 {'ID Кампании': '467',
  'Тип': 'Баннерная',
  'Платформа': 'Google',
  'Доход': '6418'},
 {'ID Кампании': '519',
  'Тип': 'Контекстная',
  'Платформа': 'Google',
  'Доход': '16659'},
 {'ID Кампании': '577',
  'Тип': 'Нативная интеграция',
  'Платформа': 'Telegram',
  'Доход': '3197'},
 {'ID Кампании': '604',
  'Тип': 'Баннерная',
  'Платформа': 'Яндекс',
  'Доход': '12617'},
 {'ID Кампании': '609',
  'Тип': 'Видеореклама',
  'Платформа': 'Instagram',
  'Доход': '34062'},
 {'ID Кампании': '615',
  'Тип': 'Контекстная',
  'Платформа': 'Яндекс',
  'Доход': '17726'},
 {'ID Кампании': '623',
  'Тип': 'Соцсети',
  'Платформа': 'Google',
  'Доход': '1393'},
 {'ID Кампании': '646',
  'Тип': 'Поисковая оптимизация',
  'Платформа': 'Google',
  'Доход': '12564'},
 {'ID Кампании': '656',
  'Тип': 'Нативная интеграция',
  'Платформа': 'Telegram',
  'Доход': '3972'},
 {'ID Кампании': '657',
  'Тип': 'Контекстная',
  'Платформа': 'Вконтакте',
  'Доход': '10692'},
 {'ID Кампании': '664',
  'Тип': 'Контекстная',
  'Платформа': 'Telegram',
  'Доход': '32374'},
 {'ID Кампании': '674',
  'Тип': 'Нативная интеграция',
  'Платформа': 'Яндекс',
  'Доход': '20766'},
 {'ID Кампании': '695',
  'Тип': 'Поисковая оптимизация',
  'Платформа': 'Вконтакте',
  'Доход': '6660'},
 {'ID Кампании': '747',
  'Тип': 'Контекстная',
  'Платформа': 'Яндекс',
  'Доход': '31952'},
 {'ID Кампании': '761',
  'Тип': 'Соцсети',
  'Платформа': 'Вконтакте',
  'Доход': '15680'},
 {'ID Кампании': '768',
  'Тип': 'Соцсети',
  'Платформа': 'Instagram',
  'Доход': '21292'},
 {'ID Кампании': '777',
  'Тип': 'Поисковая оптимизация',
  'Платформа': 'Вконтакте',
  'Доход': '10846'},
 {'ID Кампании': '797',
  'Тип': 'Баннерная',
  'Платформа': 'Telegram',
  'Доход': '2546'},
 {'ID Кампании': '803',
  'Тип': 'Баннерная',
  'Платформа': 'Instagram',
  'Доход': '24469'},
 {'ID Кампании': '807',
  'Тип': 'Соцсети',
  'Платформа': 'Яндекс',
  'Доход': '12460'},
 {'ID Кампании': '819',
  'Тип': 'Баннерная',
  'Платформа': 'Яндекс',
  'Доход': '24775'},
 {'ID Кампании': '858',
  'Тип': 'Контекстная',
  'Платформа': 'Telegram',
  'Доход': '13794'},
 {'ID Кампании': '860',
  'Тип': 'Контекстная',
  'Платформа': 'Telegram',
  'Доход': '42225'},
 {'ID Кампании': '880',
  'Тип': 'Контекстная',
  'Платформа': 'Instagram',
  'Доход': '5963'},
 {'ID Кампании': '883',
  'Тип': 'Контекстная',
  'Платформа': 'Вконтакте',
  'Доход': '36654'},
 {'ID Кампании': '900',
  'Тип': 'Контекстная',
  'Платформа': 'Telegram',
  'Доход': '26175'},
 {'ID Кампании': '914',
  'Тип': 'Видеореклама',
  'Платформа': 'Яндекс',
  'Доход': '4482'},
 {'ID Кампании': '954',
  'Тип': 'Соцсети',
  'Платформа': 'Вконтакте',
  'Доход': '24595'},
 {'ID Кампании': '987',
  'Тип': 'Соцсети',
  'Платформа': 'Google',
  'Доход': '1095'},
 {'ID Кампании': '1050',
  'Тип': 'Нативная интеграция',
  'Платформа': 'Telegram',
  'Доход': '14953'},
 {'ID Кампании': '1057',
  'Тип': 'Нативная интеграция',
  'Платформа': 'Яндекс',
  'Доход': '8121'},
 {'ID Кампании': '1060',
  'Тип': 'Поисковая оптимизация',
  'Платформа': 'Вконтакте',
  'Доход': '7021'},
 {'ID Кампании': '1064',
  'Тип': 'Поисковая оптимизация',
  'Платформа': 'Вконтакте',
  'Доход': '19852'},
 {'ID Кампании': '1070',
  'Тип': 'Соцсети',
  'Платформа': 'Вконтакте',
  'Доход': '4853'},
 {'ID Кампании': '1072',
  'Тип': 'Контекстная',
  'Платформа': 'Google',
  'Доход': '6126'},
 {'ID Кампании': '1099',
  'Тип': 'Баннерная',
  'Платформа': 'Instagram',
  'Доход': '1973'},
 {'ID Кампании': '1102',
  'Тип': 'Контекстная',
  'Платформа': 'Telegram',
  'Доход': '38563'},
 {'ID Кампании': '1104',
  'Тип': 'Контекстная',
  'Платформа': 'Telegram',
  'Доход': '11355'},
 {'ID Кампании': '1117',
  'Тип': 'Баннерная',
  'Платформа': 'Instagram',
  'Доход': '33591'},
 {'ID Кампании': '1145',
  'Тип': 'Соцсети',
  'Платформа': 'Telegram',
  'Доход': '17430'},
 {'ID Кампании': '1154',
  'Тип': 'Соцсети',
  'Платформа': 'Telegram',
  'Доход': '1411'},
 {'ID Кампании': '1163',
  'Тип': 'Поисковая оптимизация',
  'Платформа': 'Яндекс',
  'Доход': '25876'},
 {'ID Кампании': '1164',
  'Тип': 'Баннерная',
  'Платформа': 'Яндекс',
  'Доход': '4210'},
 {'ID Кампании': '1165',
  'Тип': 'Поисковая оптимизация',
  'Платформа': 'Instagram',
  'Доход': '29206'},
 {'ID Кампании': '1175',
  'Тип': 'Контекстная',
  'Платформа': 'Telegram',
  'Доход': '20408'},
 {'ID Кампании': '1227',
  'Тип': 'Нативная интеграция',
  'Платформа': 'Яндекс',
  'Доход': '18838'},
 {'ID Кампании': '1231',
  'Тип': 'Нативная интеграция',
  'Платформа': 'Instagram',
  'Доход': '22011'},
 {'ID Кампании': '1232',
  'Тип': 'Контекстная',
  'Платформа': 'Google',
  'Доход': '19417'}]

In [21]:
#@title ✏️ Проверка: чтобы проверить свое решение запустите код в этой ячейке
correct_answer = answers[7]

campaigns = campaign_generator('campaign_data.csv', 'Москва', 48000)
user_answer = []
for campaign in campaigns:
    user_answer.append(campaign)

try:
    assert str(user_answer) == correct_answer
except AssertionError:
    print('Ответы не совпадают')
else:
    print('Поздравляем, Вы справились!')

Поздравляем, Вы справились!

In [22]:
#@title ✏️ Еще одна проверка: чтобы проверить свое решение запустите код в этой ячейке
correct_answer = answers[8]

campaigns = campaign_generator('campaign_data.csv', 'Казань', 47000)
user_answer = []
for campaign in campaigns:
    user_answer.append(campaign)

try:
    assert str(user_answer) == correct_answer
except AssertionError:
    print('Ответы не совпадают')
else:
    print('Поздравляем, Вы справились!')

Поздравляем, Вы справились!